media: assets/media

content:
  - name: cities
    label: Kommuner
    type: collection
    path: _cities
    format: yaml-frontmatter
    view:
      primary: title
      fields:
        - title
        - email
    fields:
      - name: title
        label: Titel
        type: string
        required: true
      - name: email
        label: E-post
        type: string
      - name: website
        label: Webbsida
        type: string
      - name: flyer_link
        label: Länk till flyer
        type: string
      - name: candidate_lists
        label: Kandidatlistor
        type: list
        item:
          type: object
          fields:
            - name: title
              label: Titel
              type: string
              required: true
            - name: ballot_link
              label: Länk till valsedel
              type: string
            - name: candidates
              label: Kandidater
              type: list
              item:
                type: string

  - name: settings
    label: Sidinställningar
    type: file
    path: _config.yml
    format: yaml
    fields:
      - name: title
        label: Sidtitel
        type: string
      - name: description
        label: Sidbeskrivning
        type: string
      - name: url
        label: Sidans URL
        type: string
