title: Kommunistiska Partiet
description: Valsida
url: ""
baseurl: ""
logotype: https://kommunisterna.org/sites/all/themes/responsive/images/logotyp-hemsida4.png

collections:
  cities:
    output: true
    permalink: /:slug/

defaults:
  - scope:
      path: ""
      type: "cities"
    values:
      layout: "city"

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .pages.yml
