title: Valet 2026
description: Kommunistiska Partiets valsida för 2026
url: "https://val.kommunisterna.org"
baseurl: ""
image: https://val.kommunisterna.org/assets/media/frontbanner.webp

collections:
  cities:
    output: false

defaults:

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .pages.yml
